version: "3.5"

services:
  onBoard_wordpress_db:
    image: mysql:5.7
    volumes:
      - onBoard_wordpress_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3308:3306"

  onBoard_phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - onBoard_wordpress_db
    ports:
      - 8383:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
      PMA_HOST: onBoard_wordpress_db

  onBoard_wp:
    depends_on:
      - onBoard_wordpress_db
    image: wordpress:latest
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php 
      - ./wp-content/:/var/www/html/wp-content/
    ports:
      - "8003:80"
    restart: always
volumes: 
  onBoard_wordpress_db_data: